[package]
name = "gameforge-platform"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
winit = "0.30"
softbuffer = "0.4"
gameforge-runtime = { path = "../runtime" }

[dev-dependencies]
gameforge-renderer2d = { path = "../renderer2d" }
gameforge-math = { path = "../math" }
